### ISSUE TITLE
Building the MEX file

### ISSUE THREAD

**Issue by NoamGit** [boyali/matMYO#1]
Hi boyali,

Great working trying to move MYO to the MATLAB environment!
I've tried to run the Build_MYO_Mex.m (using Windows SDK  7.1) and recieved the following error:

Error using mex
myo_2c_sfunc.cpp
c:\users\noam\documents\myomatlabsdk\myo_class2a.hpp(30) : error C2864: 'Frame::ecounter' : only static const integral data members can be initialized within a class
c:\users\noam\documents\myomatlabsdk\myo_class2a.hpp(31) : error C2864: 'Frame::acounter' : only static const integral data members can be initialized within a class
c:\users\noam\documents\myomatlabsdk\myo_class2a.hpp(32) : error C2864: 'Frame::gcounter' : only static const integral data members can be initialized within a class
c:\users\noam\documents\myomatlabsdk\myo_class2a.hpp(202) : error C2864: 'DataCollector::ecounter' : only static const integral data members can be initialized within a class
c:\users\noam\documents\myomatlabsdk\myo_class2a.hpp(203) : error C2864: 'DataCollector::acounter' : only static const integral data members can be initialized within a class
c:\users\noam\documents\myomatlabsdk\myo_class2a.hpp(204) : error C2864: 'DataCollector::gcounter' : only static const integral data members can be initialized within a class

Do you have any ideas how to solve this?

Noam

**Comment by boyali** [comment]
Hello

I really don't have any solution for this error, many people could use it.
May be Matlab version or C++ Windows SDK. You may try other C++ compilers

Thank you

**Comment by NoamGit** [comment]
Thanks,

What compiler do you use?

Noam

**Comment by boyali** [comment]
I used VC 2012.

**Comment by NoamGit** [comment]
Works great with VC 2013 C++. 
As I understand this is a link between the C++ datacollector to matlab. There is no class for setting acquisition parameters from matlab right? If not, how can set this without changing the cpp file?

**Comment by boyali** [comment]
I didn't understand your questions. There is a MYOMat forum where people
already discussed some of the issues you are asking.

Thanks
